// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD74T6dy3800lKxrkhlKkJRw-Y7jMl6EOQ',
    appId: '1:49458311327:web:17777fd71794d12dc372aa',
    messagingSenderId: '49458311327',
    projectId: 'sixty7-afa11',
    authDomain: 'sixty7-afa11.firebaseapp.com',
    storageBucket: 'sixty7-afa11.appspot.com',
    measurementId: 'G-SHTXGB931C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI-SNZsgkIWMJnq46zRyUGG-SJ3ZHrRu4',
    appId: '1:49458311327:android:fc0ec97d736a29b4c372aa',
    messagingSenderId: '49458311327',
    projectId: 'sixty7-afa11',
    storageBucket: 'sixty7-afa11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCegd0PYLTFQYqonUSlQ2k9b-znCxLJIQw',
    appId: '1:49458311327:ios:8b564f8fc5e56993c372aa',
    messagingSenderId: '49458311327',
    projectId: 'sixty7-afa11',
    storageBucket: 'sixty7-afa11.appspot.com',
    iosBundleId: 'com.example.sixty7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCegd0PYLTFQYqonUSlQ2k9b-znCxLJIQw',
    appId: '1:49458311327:ios:8b564f8fc5e56993c372aa',
    messagingSenderId: '49458311327',
    projectId: 'sixty7-afa11',
    storageBucket: 'sixty7-afa11.appspot.com',
    iosBundleId: 'com.example.sixty7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD74T6dy3800lKxrkhlKkJRw-Y7jMl6EOQ',
    appId: '1:49458311327:web:e8fbd701743a8d11c372aa',
    messagingSenderId: '49458311327',
    projectId: 'sixty7-afa11',
    authDomain: 'sixty7-afa11.firebaseapp.com',
    storageBucket: 'sixty7-afa11.appspot.com',
    measurementId: 'G-KZW7XLC6FC',
  );
}
